4 signup
GSG-G13/gym-server pull request #15
Opened 2023-06-13 13:52 UTC by AhmedMughessib

2023-06-13 15:09 UTC, abeerAyad approved these changes

2023-06-13 16:10 UTC, HamdyPs approved these changes

2023-06-13 16:18 UTC, HamdyPs approved these changes
its still need more fix and more check also needs validation but for now its ok

2023-06-13 21:19 UTC, AdhamHaisami requested changes

2023-06-13 21:19 UTC, AdhamHaisami commented on src/controllers/user/signup.ts
>  const signupController = async (req: Request, res: Response): Promise<void> => {
req type must not be Request, it should be the interface we built

2023-06-13 21:19 UTC, AdhamHaisami commented on src/controllers/user/signup.ts
> +    console.log(hashedPassword);
delete the console log

2023-06-13 21:19 UTC, AdhamHaisami commented on src/controllers/user/signup.ts
> +    console.log(error, 'err');
use the custom error not just log the error

2023-06-13 21:19 UTC, AdhamHaisami commented on src/controllers/user/signup.ts
>      await User.create({
where is the validation before creating a user into the db

2023-06-13 21:19 UTC, AdhamHaisami commented on src/controllers/user/signup.ts
>      await User.create({
also you must check if the email exists in the database before adding new one, since the email is uniqe

2023-06-14 09:00 UTC, AhmedMughessib commented on src/controllers/user/signup.ts
>      await User.create({
i checked if the email exist, didn't do the validation yet

2023-06-14 09:50 UTC, AhmedMughessib commented on src/controllers/user/signup.ts
>      await User.create({
the validation will be done by Abeer

2023-06-14 13:05 UTC, HamdyPs approved these changes

2023-06-14 13:08 UTC, heleena-fadi approved these changes

2023-06-14 13:56 UTC, abeerAyad approved these changes

2023-06-14 13:56 UTC, heleena-fadi approved these changes

2023-06-14 13:57 UTC, HamdyPs approved these changes

2023-06-14 14:00 UTC, AdhamHaisami approved these changes

2023-06-14 14:00 UTC, merged