review feature post method
GSG-G13/gym-server pull request #25
Opened 2023-06-14 20:12 UTC by AhmedMughessib

I created the review database schema, router, and controller. 
also, I edited the checkout file and changed the name of the token

2023-06-14 22:28 UTC, HamdyPs requested changes

2023-06-14 22:28 UTC, HamdyPs commented on src/controllers/reviews/addreview.ts
> +    await Review.create({
you need to check if there is a review with same review id and user id , if its true you need to stop creating, else create review

2023-06-15 10:09 UTC, HamdyPs approved these changes

2023-06-15 10:30 UTC, abeerAyad approved these changes

2023-06-15 10:40 UTC, heleena-fadi approved these changes

2023-06-15 10:40 UTC, HamdyPs approved these changes

2023-06-15 10:42 UTC, AdhamHaisami approved these changes

2023-06-15 10:42 UTC, merged