get product by category
GSG-G13/gym-server pull request #41
Opened 2023-06-15 13:35 UTC by abeerAyad

Relates#38
Closes

2023-06-15 13:48 UTC, HamdyPs requested changes

2023-06-15 13:48 UTC, HamdyPs commented on src/controllers/products/getProductByCategory.ts
> +    res.status(400).json({ error });
use next custom error

2023-06-17 14:32 UTC, HamdyPs approved these changes

2023-06-17 17:00 UTC, heleena-fadi requested changes

2023-06-17 17:00 UTC, heleena-fadi commented on src/controllers/products/getProductByCategory.ts
> +const getProductByCategory = async (req: Request, res: Response) => {
const getProductByCategory = async (req: Request, res: Response , next: NextFunction) => 
(you should use custom Error here By passing next to use it on catch later ..

2023-06-17 17:00 UTC, heleena-fadi commented on src/controllers/products/getProductByCategory.ts
> +    res.status(400).json({ error });
instead of res.status(400).json({ error });
 add custom Error..like this
next(new CustomError(500, error.message))

2023-06-18 21:10 UTC, AdhamHaisami requested changes

2023-06-18 21:10 UTC, AdhamHaisami commented on src/routers/product.ts
> +<<<<<<< HEAD
you must delete these lines

2023-06-19 08:31 UTC, HamdyPs approved these changes

2023-06-19 08:31 UTC, AdhamHaisami approved these changes

2023-06-19 08:32 UTC, AhmedMughessib approved these changes

2023-06-19 08:32 UTC, merged