get reviews by product ID
GSG-G13/gym-server pull request #48
Opened 2023-06-16 16:20 UTC by AhmedMughessib

2023-06-17 13:28 UTC, HamdyPs approved these changes
this branch to get all the reviews of one product, and its done well

2023-06-17 17:11 UTC, HamdyPs requested changes

2023-06-17 17:11 UTC, HamdyPs commented on src/controllers/reviews/getreviews.ts
> +    res.status(200).json(productReviews);
send data as an object with a message that getting all reviews about 1 product successfully

2023-06-17 17:18 UTC, heleena-fadi approved these changes

2023-06-18 07:29 UTC, HamdyPs approved these changes

2023-06-18 09:37 UTC, AdhamHaisami approved these changes

2023-06-18 09:37 UTC, merged