42 delete class
GSG-G13/gym-server pull request #56
Opened 2023-06-17 18:18 UTC by heleena-fadi

delete class controllers and router

2023-06-17 18:20 UTC, HamdyPs approved these changes

2023-06-17 23:45 UTC, AdhamHaisami commented on src/routers/class.ts
> +classRouter.delete('/:id', deleteClass);
only admins can delete class, we must check that

2023-06-17 23:47 UTC, AdhamHaisami requested changes

2023-06-17 23:47 UTC, AdhamHaisami commented on src/routers/class.ts
> +classRouter.delete('/:id', deleteClass);
only admins can delete class, we must check that

2023-06-18 08:48 UTC, HamdyPs approved these changes

2023-06-18 09:23 UTC, HamdyPs approved these changes

2023-06-18 09:27 UTC, AdhamHaisami approved these changes

2023-06-18 09:27 UTC, merged