update class controller and router
GSG-G13/gym-server pull request #58
Opened 2023-06-17 18:36 UTC by heleena-fadi

Relates #57
Closes #57

2023-06-17 18:41 UTC, HamdyPs approved these changes

2023-06-18 08:24 UTC, HamdyPs requested changes

2023-06-18 08:24 UTC, HamdyPs commented on src/routers/class.ts
> +classRouter.put('/:id', updateClass);
only admin can update class

2023-06-18 08:48 UTC, HamdyPs approved these changes

2023-06-18 09:31 UTC, AdhamHaisami approved these changes

2023-06-18 09:31 UTC, AdhamHaisami requested changes
resolve conflict

2023-06-18 09:58 UTC, AhmedMughessib approved these changes

2023-06-18 10:14 UTC, HamdyPs approved these changes

2023-06-18 10:24 UTC, merged