add subscribtion controller and router
GSG-G13/gym-server pull request #60
Opened 2023-06-17 20:01 UTC by heleena-fadi

Relates #59
Closes #59

2023-06-17 20:10 UTC, HamdyPs approved these changes

2023-06-18 08:14 UTC, HamdyPs requested changes

2023-06-18 08:14 UTC, HamdyPs commented on src/controllers/subscriptions/addSubscription.ts
> +    const { price, status } = req.body;
we won't get the status from client

2023-06-18 08:14 UTC, HamdyPs commented on src/database/subscriptionSchema.ts
> +  price: {
the price of the class must be in the class itself

2023-06-18 08:14 UTC, HamdyPs commented on src/interfaces/subscription.ts
> +    price: Number
no need for price anymore

2023-06-18 08:14 UTC, HamdyPs commented on src/routers/subscription.ts
> +SubscriptionRouter.post('/:userId', addSubscription);
this isn't user id. it's a class id

2023-06-18 08:14 UTC, HamdyPs commented on src/routers/subscription.ts
> +SubscriptionRouter.post('/:userId', addSubscription);
check if the user signed in

2023-06-18 08:39 UTC, HamdyPs approved these changes

2023-06-18 09:34 UTC, AdhamHaisami approved these changes

2023-06-18 09:34 UTC, merged